---
title: "result_analysis"
output: html_document
---

## data preprocess

```{r}
library(dplyr)
library(tidyr)

setwd("/Users/jay/workspace/my_github/ClusterwiseJICA_v2")
load("./collect_result/comprehensive_results.RData")

```

```{r}
str(results_df)
```

```{r}
result_small <- results_df[, c("method", "complex", "K", "E","VAF","Qvect_string","ari","tucker_S")]
```

```{r}
str(result_small)
```

## compare ARI

```{r}
library(dplyr)
library(tidyr)

factors <- c("K", "complex", "E", "VAF", "Qvect_string", "method")

for (factor in factors) {
  cat("==== Grouped by:", factor, "====\n")
  print(
    result_small %>%
      group_by(across(all_of(factor))) %>%
      summarise(
        mean_ari = round(mean(ari, na.rm = TRUE), 4),
        sd_ari = round(sd(ari, na.rm = TRUE), 4),
        mean_tucker_S = round(mean(tucker_S, na.rm = TRUE), 4),
        sd_tucker_S = round(sd(tucker_S, na.rm = TRUE), 4),
        .groups = "drop"
      )
  )
  cat("\n")
}


```

```{r}
# Compare ARI across methods for each Qvect_string
ari_Q_method <- result_small %>%
  group_by(Qvect_string, method) %>%
  summarise(
    mean_ari = round(mean(ari, na.rm = TRUE), 4),
    .groups = "drop"
  ) %>%
  pivot_wider(
    names_from = method,
    values_from = mean_ari
  ) %>%
  arrange(Qvect_string)
ari_Q_method
```


```{r}
ari_complex_method <- result_small %>%
  filter(method %in% c("chull", "vaf")) %>%  # keep only these two methods
  group_by(complex, method) %>%
  summarise(
    mean_ari = round(mean(ari, na.rm = TRUE), 4),
    .groups = "drop"
  ) %>%
  pivot_wider(
    names_from = method,
    values_from = mean_ari
  ) %>%
  arrange(complex)
ari_complex_method
```


```{r}
# Run ANOVA with multiple factors
anova_1 <- aov(ari ~ E + Qvect_string + method + VAF, data = result_small)

# Show the ANOVA table
summary(anova_1)
```



```{r}
# Run ANOVA with multiple factors
anova_inter <- aov(ari ~ E * Qvect_string * method * VAF * complex, data = result_small)

# Show the ANOVA table
summary(anova_inter)
```


```{r}
mean_ari_vaf <- result_small %>%
  group_by(method, VAF) %>%
  summarise(mean_ari = mean(ari, na.rm = TRUE)) %>%
  arrange(method, VAF)

mean_ari_vaf


```


```{r}
library(ggplot2)

# Histogram + density plot for ARI
ggplot(result_small, aes(x = ari)) +
  geom_histogram(aes(y = ..density..), bins = 30, fill = "skyblue", color = "black", alpha = 0.7) +
  geom_density(color = "blue", size = 1) +
  xlab("ARI") +
  ylab("Density") +
  theme_minimal()
```

```{r}
ggplot(results_df, aes(x = method, y = ari, fill = method)) +
  geom_violin(trim = FALSE, alpha = 0.7) +
  geom_boxplot(width = 0.05, fill = "white", outlier.size = 2) + 
  xlab("Method") +
  ylab("ARI") +
  theme_minimal() +
  theme(legend.position = "none")
```




## compare Tucker

```{r}
library(ggplot2)

# Histogram + density plot for Tucker
ggplot(result_small, aes(x = tucker_S)) +
  geom_histogram(aes(y = ..density..), bins = 30, fill = "skyblue", color = "black", alpha = 0.7) +
  geom_density(color = "blue", size = 1) +
  xlab("Tucker") +
  ylab("Density") +
  theme_minimal()
```



```{r}
ggplot(results_df, aes(x = method, y = tucker_S, fill = method)) +
  geom_violin(trim = FALSE, alpha = 0.7) +
  geom_boxplot(width = 0.05, fill = "white", outlier.size = 2) + 
  xlab("Method") +
  ylab("Tucker") +
  theme_minimal() +
  theme(legend.position = "none")
```

```{r}
# Compare tucker across methods for each Qvect_string
tucker_Q_method <- result_small %>%
  group_by(Qvect_string, method) %>%
  summarise(
    mean_ari = round(mean(tucker_S, na.rm = TRUE), 4),
    .groups = "drop"
  ) %>%
  pivot_wider(
    names_from = method,
    values_from = mean_ari
  ) %>%
  arrange(Qvect_string)
tucker_Q_method
```

```{r}
# Run ANOVA with multiple factors
anova_inter <- aov(tucker_S ~ E * Qvect_string * method * VAF * complex, data = result_small)

# Show the ANOVA table
summary(anova_inter)
```

```{r}
tucker_complex_method <- result_small %>%
  filter(method %in% c("chull", "vaf")) %>%  # keep only these two methods
  group_by(complex, method) %>%
  summarise(
    mean_tucker = round(mean(tucker_S, na.rm = TRUE), 4),
    .groups = "drop"
  ) %>%
  pivot_wider(
    names_from = method,
    values_from = mean_tucker
  ) %>%
  arrange(complex)
tucker_complex_method
```



